### ISSUE TITLE
Malformed confirmation link

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#105]
Just received one of the 'yes, please send my letter to my MP' emails that we often get in response to our confirmation email. 

I noticed the confirmation link was malformed (but I don't know if this might have happened in the act of replying, or if it was like that when the user received it).  It looks like this: www.writetothem.c   https://om/C/&lt;messageid>

**Comment by dracos** [comment]
Closing as overlaps with #56 and nothing recent.
