### ISSUE TITLE
Add a 'satisfaction' question to the questionnaire (simply to prevent support mail)

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/writetothem#11]
Approx. 1-2 users/ week email to ask WTT to add some sort of 'were you happy with your reply' question to the questionnaire (which is currently 'did you get a reply?' Yes/No). There are a number of issues with implementing this, from trying to minimise confusion (some find the current questionnaire confusing) to avoiding abuse (especially, one would imagine, from those who receive a well-researched response which fundamentally disagrees with the original query, or those receiving stock replies). However, it should certainly be considered.

**Comment by MyfanwyNixon** [comment]
"  maybe you would consider putting an 'unsatisfactory response'
     option on your follow up questionnaire? I think it is important
     to know the representatives that, for instance, wilfully ignore
     questions or pass them off to civil servants to give you
     copy-paste answers of little significance. It seems that this
     kind of 'political' answers is putting people off as much as
     being ignored."

**Comment by MyfanwyNixon** [comment]
"My MP doesn't share my
     views or values but she always respond to any communication,
     even if she just toes her party line . So I would love it if
     there was an option to only report back if my MP DIDN'T respond
     to communication, which so far has never happened."

**Comment by MyfanwyNixon** [comment]
User comment: "It's all well and good having the ability to write to them - but
surely you could capture more information about the type of response
they give - seriously non-committal in the case of mine on a range of
issue - can't help to think that they work for their powerful vested
interests rather than for me - if they were up front then well you
know where you stand (but politicians being upfront - hmm - snow in
august perhaps).

Is there any work being done to improve not just whether they reply -
but to some how capture the value of their replies - otherwise it's
just a polite way to tell you to **** off to be honest - disheartening
and not worth the time."

**Comment by MyfanwyNixon** [comment]
User comment: "I had assumed when you said 'questionnaire' I would have some way of voicing my deep discontent in other questions.  My MP did reply, but she did not address a single one of my points or comments.  She basically ignored everything I said and said that if I had any concerns I could go into her office, and she had a local office for this reason.  Ignoring the  fact I told her I was disabled and virtually house bound.  I DO NOT want such a shoddy response to appear as something in her favour.  Yes I received a reply, no it was not a satisfactory response.  If you can, please amend this stat to reflect the negativity I feel about the response.  It  would perhaps help if you added a second question as to degree of satisfaction?"

**Comment by MyfanwyNixon** [comment]
User comment: "I did use your service and was pleased with it.
However, the reply I received from my MP  was erudite BUT it did not in anyway answer the two points that I raised with him. [..]
In your satisfaction survey  perhaps you could ask  " has your  query/questions been answered?  Yes or No". This would be a good indicator if there is any life left in our democracy."

**Comment by MyfanwyNixon** [comment]
"All though I did get a reply from my MP it has so much
     'spin' that it is, at best, highly misleading. Outside of
     politics it would be called lying through your teeth, refusing
     to accept responsibility for ones own actions and an attempt to
     re-write history!  The main point was ignored but there was a
     side of A4 touching on peripheral matters.

     As your form stands I have to tick the box saying I got a
     reply. Unfortunately the reply was actually a waste of tax
     payers money, as explained above.

     While opinions on political matters are always going to be
     somewhat personal and therefore difficult to quantify, I wonder
     if there's some way to ask if the reply is considered as being
     an honest attempt at explanation (even if the questioner
     disagrees with what's said) or an irrelevant fudging just to
     get a reputation of replying.

     My reply from Julian Smith MP is worthy of framing and starring
     in a 'bullshit' exhibition, yet he gets a tick for 'replying'."

**Comment by MyfanwyNixon** [comment]
> eventually I  received an response from what i assume was a secretary who
     [...] says [my MP] will write to me soon [not holding my breath].

   >  YOu might want to add a box to your survey to cover such eventualities - i think it might be very revealing!

   >  How many people are clicking link "A" or not clicking at all  when they have encountered a similar situation?

 >    Its just a suggestion, but i do think it could be useful to you and "informatve" of the Mps

**Comment by MyfanwyNixon** [comment]
"Her reply consisted of a slice of Hansard, and she has not responded to my supplementary questions. Her response compares unfavourably to her predecessor who was prompt and pertinent. My clicking of the button "Did they reply" needs this qualification."

**Comment by MyfanwyNixon** [comment]
> "I DID get a reply, but the MP basically dismissed my letter and said he didnt believe it was in the public interest to do what I was requesting. 

 > It would be useful to have another category "did the MPs reply basically dismiss your point of view" - as otherwise, it may appear that MPs are being receptive - when they are just being arrogant ar** holes !!!!

**Comment by MyfanwyNixon** [comment]
User feedback: 

> When I read your email, my first response was that I
     didn't need to respond as I have had no answer from the
     organisation that I asked my representative about. Then I
     reread your email and realised that you were asking only about
     a response from my representative. Your email, when read
     properly, is correct but you might give my initial thought a
     little consideration.

     My issue is complex and if my representative  is unable to get
     a response from the organisation, I have only one option to
     take: a sort of "nuclear option". Thus my first reading of your
     email was "coloured" by that thought. I do not think I would be
     unique in that.

     Bear in mind that your efforts are to be lauded but really
     people like me just want a response from the organisation that
     we have an issue with; you are not primary to that.

**Comment by MyfanwyNixon** [comment]
User comment:

> I did receive a reply but it was from someone who works for [an organisation] not from him.  The letter only contained Conservative Party policy and was impersonal and very unsatisfactory.   I replied to this letter with a follow up but have received neither acknowledgement nor reply to that letter.  I am writing this email as neither of the my responses fit the bill.

**Comment by MyfanwyNixon** [comment]
User comment:

>I always get a longish reply, but recently I get the impression that his replies are general (Syria ? Oh ! send reply 2C) replies and do not specifically answer my points. Therefore, I do acknowledge his reply in your follow-up e-mails; but there's no room to tell you if I think he specifically answered my points.

**Comment by MyfanwyNixon** [comment]
User suggestion:

> How about this option for the questionnaire that might keep things simple?

> Did you get a response?  Yes  No
> Were you happy with the response?  Yes  No

> If no, please expand (15 words) max... 

> Or, instead of a brief reason, offer a few choices like    'useless MP' (lol)......... 'Other' reason, 
(I have such a dim view of our system that I can only think of this one!)
So the results would  still be collatable ?  and we could start an MP fail chart :)

**Comment by MyfanwyNixon** [comment]
User comment:

>  The MP replied to my e-mail, BUT NOT TO MY QUESTION !
     No doubt he  will go down in your database as a GOOD MP who
     replies to a constituents question.
     Whereas he DID NOT reply, he sent a standardised advertisement
     for the promotion of Fracking in the UK, as an answer to all
     Energy needs.
     Typical MP behaviour of NEVER answering a question.
     It would make more sense if instead of simply asking "Did you
     get a reply" you ask " Did he answer your query" ?

**Comment by MyfanwyNixon** [comment]
User comment:
>  I just wanted to say that although i've just clicked on your link to say my mp didnt reply to my letter re bombing syria, he did keep his constituents fully informed of his thinking during the debate and his decision via twitter and facebook and that i was quite happy with that. Maybe you should have a third option for not having a letter back but being kept informed via social media?

**Comment by MyfanwyNixon** [comment]
>Your survey of which MP's are Google at replying to
     letters doesn't really a good guide.
     For example, my MP Just Tomlinsonmp is very high in the list.
     A recent reply from him to my wife didn't a dress the real
     issues raised. All she got was a paternising reply and why he
     can't do anything and list useless Web sites to get answers or
     to join a FI group. Just waste of time and he even didn't know
     the subject as he is also a minister of disabled but didn't
     even how the procedure or who to contact in the local con
     administrated council.

>  I suggest you need additional column to say how good their
     reply.

**Comment by MyfanwyNixon** [comment]
> Have you ever considered also asking whether you were happy  with the response? I feel this could be useful in tracking how well our representatives are representing our views.

**Comment by MyfanwyNixon** [comment]
> I clicked the link to show I had received a reply from my MP, but would have liked a box to say whether or not I was happy with the response.  The reality is I am not happy as he didn't answer the question and the legislation he quoted me is incorrect and does not apply to the issue I wrote to him about.

**Comment by MyfanwyNixon** [comment]
> Your follow up email requesting if my MP had responded to my email doesn't have enough options.  Yes, he sent me a letter, but it didn't answer my question.  It was just a stock response that must have been written by the department involved.  I don't want my MP to get good marks in  your performance table for replying in this way.

**Comment by MyfanwyNixon** [comment]
> My MP Maria Caulfield has a website with a page responding all the writing campaigns giving her position and an update on the current state of that.  It is a very helpful way of treating a campaign, above all cost effective.  The cost of writing back to everyone who writes in a campaign really was a concern to me, especially if a letter was preceded by a holding acknowledgment.

> So, I could not reply to either of your requests for feedback, as this method does not fit in with either, but for me is the best way to deal with a mass campaign.  That leaves the MP free to respond personally to one-off issue letters, which Maria has done to me on two occasions now, concerning medical/NHS issues which I have raised with her as nurse-to-nurse.

**Comment by MyfanwyNixon** [comment]
> I didn't answer your latest survey about a letter I sent to my MP because the survey didn't offer the option "I have had a reply to the letter but not to any of the points I made in it".

**Comment by struan** [comment]
So, I could do with some copy wrangling on this. My starter for ten efforts are here:

https://docs.google.com/document/d/1pWmWLvc4tLp2qdloB7FXnl8GrORJBNUzpWYr7sn1fLc/edit#

I am sure people can do better. ( @MyfanwyNixon / @abimysoc )

We probably also want to consider how this will effect the responsiveness stats but I would suggest that is a separate ticket.

**Comment by MyfanwyNixon** [comment]
Here's a slight variation on the usual suggestions:

> I would like to make a suggestion that in your email to collect feedback after I have written to my MP, you add a third option.
> 
>      Currently you ask if the MP sent a reply or only acknowledged
>      receipt of my letter. A third option, which was the case in my
>      situation could distinguish between a personal reply and a form
>      letter with no salutation (i.e. no Dear ..., Hello, etc. )

I can see that we could discuss this infinitely though, if we try to encompass every single scenario. At the moment I think 'did the reply answer your question' is an adequate measure.

**Comment by MyfanwyNixon** [comment]
> I note that you asked whether we had a reply from out
     MP but I was extremely dissatisfied in the way the whole matter
     was handled. [...] His answer completely ignored all my evidence
     and he just "rolled over " and dropped the whole thing when the
     council refused to acknowledge my complaints. I found this
     insulting and unsupportive. You do not give a "Are you
     Satisfied with the Result?" Button bit you should! The whole
     thing was a farce and my evidence was ignored.

**Comment by MyfanwyNixon** [comment]
>  I have noticed that when I write to my MP,  I get a
     quick acknowledgement followed by a "canned response"- often in
     the form of a bland party policy statement- a few days later.
     If I challenge that and press my particular point I get no
     further response. So telling writetothem team that I had a
     response does not give an accurate picture. A better method
     would be to find out if the MP actually addressed the issue
     properly.  A stock answer that MPs send out is no more valuable
     than the acknowledgement.

**Comment by MyfanwyNixon** [comment]
> I wrote to my MP and confirmed he replied - from this
     you assume he's doing his job!!!

>The fact that my MP's reply was wholly unsatisfactory and
     totally failed to answer any my questions seems to be
     irrelevant to you - it appears to you that he is doing his
     job??? I don't think so!

>Why not include some qualitative analysis - ask me to rate the
     reply I received between 1 an 10 so it can be established if
     our representatives are actually doing more than just paying
     lip-service when answering questions

**Comment by MyfanwyNixon** [comment]
In the spirit of assessing whether we've 'fixed' the user support issue of people writing to say the questionnaire doesn't fit their needs, I'm just recording a user's comment.

> Yes he always replies but sometimes just the party line never any action

**Comment by MyfanwyNixon** [comment]
>  The reply questions do not cover the case when the MP refers
     one's query to a minister for a better/full answer.
     Effectively, the MP has answered but until the minister replies
     a full response has not been obtained.

**Comment by MyfanwyNixon** [comment]
> Your questionnaire is too simplistic: My MP replied using his weekly e.mail to all consituents which is very detailed. 

My response:
>The core question is really whether your MP replied in a satisfactory manner for *you* - if you feel that he did (via whatever means) then I would click 'yes'.

**Comment by MyfanwyNixon** [comment]
>I have just completed one in relation to Maria Caulfield, lewes MP, and the 'writeto them' about stopping the bombing of Alleppo.

>However ticking the 'acknowledgement only' box di not convey the full nature of her responses to the wider issue of the safety of civilians affected by the Syrian conflict. it seemed to me you needed  an 'other info' box to give this opportunity to the respondent.

>if there had been I would have said that a week or so later she responded to individuals regarding the refugee children in Calais and pledged to work with the Local Aunthority and citizens groups to ensure all the children get here and find a place of safety.

>This is to be commended in my view. 

My reply as follows, but I'm recording this to show that the new questionnaire has not stopped people from writing in to query the questionnaire's suitability for their situation :(

>As you may be aware, we've recently changed the questionnaire from a straight yes/no choice, in an attempt to cover more eventualities. Note that, as before, you can always return to our questionnaire email to change your vote, eg 'acknowledgement only' can be changed to 'full reply' should that come in later: the last input will always override any previous ones.

>From our point of view the important thing is to be able to collect clear consistent data that informs us a) whether our service is working and b) which MPs are responding to constituents. Although it's always interesting/instructive to hear the details of individual cases, on a bulk level we need the data to be really consistent for us to be able to pull those data out.

**Comment by MyfanwyNixon** [comment]
> Further to your request for information relating to whether my MP responded to my request through yourselves  in relation to the cancer treatment I wish to confirm that I did indeed receive a very timely response.
>I would also point out that the response  was very touching and personal - nothing generic about it.
>I hope this helps with your understanding of MP responses.

**Comment by MyfanwyNixon** [comment]
Matthew via IRC:
> update the contact page to a) not ask for feedback on receiving a response...?
> b) add radio icon to check if they're writing about response, and say don't bother if so

**Comment by abimysoc** [comment]
Looking at this week's emails, they're not all coming via the contact form. Other things to change would be:

* The questionnaire email comes from a do-not-reply address, yet replies to it are still let through to support (see also: [spam](https://github.com/mysociety/sysadmin/issues/743#issuecomment-233680950)).
* Don't include the support address in the text of the questionnaire email.

**Comment by dracos** [comment]
"The questionnaire email comes from a do-not-reply address, yet replies to it are still let through to support" – the first reply should get an auto-response; if that's not happening, that's a bug.

**Comment by abimysoc** [comment]
I'd be surprised if there was a bug, just that the auto-reply won't be enough to deter some people (subsequent replies get through, right?).

The auto-reply email (if I'm reading the code correctly) also has the support email address in.

**Comment by MyfanwyNixon** [comment]
Some statistics:

The new style questionnaire went live on 17 October, so I can compare user support from the last 10 days with the 10 days prior (although a longer timeframe would be preferable, so we should return to this in a few weeks, too).

8-17 October 0 user support emails about the questionnaire
18- 27 October  5 user support emails about the questionnaire

- Sent via fyr-DO-NOT-REPLY@writetothem: "Yes and she has not answered my question."
- Via support@writetothem.com: "  The reply questions do not cover the case when the MP refers
     one's query to a minister for a better/full answer."
- Via support@writetothem.com: "Your questionnaire is too simplistic"
- Via support@writetothem.com "ticking the 'acknowledgement only' box did not convey the full nature of her responses to the wider issue "
- Via support@writetothem.com "I hope this helps with your understanding of MP responses"

A slightly different issue is that some people reply because they think we're the campaign that pointed them to WTT, wanting to tell us the answer they got.
- Via support@writetothem.com: "If you want to give me a postal address I will send you a copy."

###Action
Let's try the suggestions upthread:

- [ ] update the contact page so it doesn't ask for feedback on receiving a response (maybe link to some kindly 'why not' text in the FAQs)
- [ ] add radio icon to check if they're writing about response, and say don't bother if so
- [ ] review auto-reply text to make it more clear that we don't want this kind of correspondence (core issue: the data goes towards stats so needs to be black and white & standardised, if your circumstances don't quite fit in just don't participate?)
- [ ] Consider removal of the support email address from the auto-reply text

**Comment by dracos** [comment]
The satisfaction question *was* added, and so I think this ticket should be considered done, the suggestions aren't issues or bugs with the adding of the question. Each of the actions suggested should be a new ticket, preferably, they are all separate things that can be done independently.

**Comment by MyfanwyNixon** [comment]
OK, good point, I'll split them into new tickets.

**Comment by MyfanwyNixon** [comment]
I've received an example of the questionnaire where the links have been disabled (and there's no obvious sign that they have either):

![fireshot screen capture 918 - re_ did your mp reply to your letter_ - writetothemsupport mysociety_org - mysociety mail - mail_google_com_mail_b_86](https://cloud.githubusercontent.com/assets/944656/19976252/e3cb7894-a1e6-11e6-9a71-bf1e391cce3b.jpg)

Seems logical that a user would respond to us when you see it like that.

**Comment by MyfanwyNixon** [comment]
>Message: I totally support your idea that collecting
     information on how successful the system is at eliciting
     answers from our representatives is necessary to attaining
     democratic responsiveness.  However I find the format for your
     "did they respond?" question a bit broad-brush.  In the current
     incident I did receive a reply, and it did address my issue,
     but it was from someone on my MPs staff and did not show
     evidence that he had seen it.  I understand that an M.P. in
     particular has far more mail than they can personally oversee
     and that the response that I received implicitly acknowledged
     this.  However his predecessor, Jo Swinton, was very good at
     taking an interest in constituents' concerns and providing
     evidence that she had seen the material sent out under her
     name.  I would like your "Response" form to provide a means for
     us to qualify the answers that we send to you.  I could amplify
     this matter but for now will content myself with this reply.

**Comment by MyfanwyNixon** [comment]
High levels of responses to the questionnaire email!

28 Oct - 6 November: 7 responses to the questionnaire email
7 November - 16 November: 3 responses

For some reasons, **14** responses over this weekend just past, 18-20  November.

**Comment by MyfanwyNixon** [comment]
I'm just noting this, although really I think the user is saying 'I don't agree with my MP's response' which is irrelevant for our needs really.

> I think there should be another option in your bullet
     points which says something like "yes they replied and they
     answered my question but in an unsatisfactory way"

**Comment by MyfanwyNixon** [comment]
> I answered your survey but it did not give me any
     opportunity to comment on my MP's reply. He did reply, a posted letter, and he did answer my
     question, in one sense.
>
 > But I had no opportunity to say in your survey that I found his
     reply was just a standardised put-down, in which he refused to
     say he would represent my views to the PM because he agrees with what the government is
     doing. He said why - the usual Tory woffle.
>
> Perhaps you could add to your survey, when there's been a
     reply, a simple question to allow respondents to say whether
     they felt anything was achieved, or perhaps, e.g.whether it was
     helpful/satisfactory or not...

**Comment by MyfanwyNixon** [comment]
> I think it would be better if you were to separate Q.4 - “No, but I didn’t expect/require a response”.

> My MP is [xxxx], who is nothing more than a sheep - in our experience she has always voted with the government. So although I would have liked a response, I didn’t expect one.

**Comment by MyfanwyNixon** [comment]
> You did not include "Did their PA answer on their behalf?"
