### ISSUE TITLE
broken link to Aristotle in help pages asking for MP's addresses

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/writetothem#145]
The link on 
https://github.com/mysociety/writetothem/blob/a7165a566554848951ea4284e9baa0d47dba20f0/templates/website/about-qa.html#L339
is broken… but it's not entirely clear (to me, having briefly poked around on the Guardian site a little) what the correct link is, as the link I found on the Graun site to "Aristotle home page" was itself broken.

**Comment by dracos** [comment]
Link not there now
