### ISSUE TITLE
html design for our automated emails

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#164]
Ref #11 

Much of our user support burden is because of users who respond to our automated emails. In the case of WTT, it's generally the questionnaire email.

I suggest that we may be able to minimise this effect through design - official branding and a button rather than plain text and a link may make it clearer that the message is not from a human who genuinely wants to know whether you received a reply.

**Comment by MyfanwyNixon** [comment]
Some relevant feedback from a user: "Please make the link more obvious!  Found it eventually but not obvious which link you mean!"

**Comment by MyfanwyNixon** [comment]
Have submitted a pull request that overwrites the 'our system isn't 100% reliable' line.

**Comment by zarino** [comment]
I've started work on this in https://github.com/mysociety/writetothem/pull/342

**Comment by zarino** [comment]
Question: Should the emails we send to representatives *also* be HTML emails? Or just the citizen-facing emails?

**Comment by MyfanwyNixon** [comment]
Ooh, that's an interesting one.

IMO: we want those emails to look as much like emails from a constituent, not a service, as possible. See [this convo](https://twitter.com/Lynda_Waltho/status/757854675454480384) with an MP on Twitter for a bit of relevant background (bit tricky to link to the entire thread because there are several replies to some tweets but in a nutshell she thought MPs might treat WTT emails differently than other constituent emails, either by prioritising them or by ignoring them *shrug*).

That doesn't necessarily mean no HTML, I guess, but it probably means that any HTML should still look as much like a 'normal' email as possible. That being the case, is there any benefit in HTMLising these mails?

**Comment by zarino** [comment]
> IMO: we want those emails to look as much like emails from a constituent, not a service, as possible. 

That was my initial reaction too. Maybe we leave those emails as-is. It's not like there are buttons or things we want them to click (which was the main reason for upgrading to HTML templates for the confirmation and questionnaire emails).

**Comment by zarino** [comment]
The pull request at https://github.com/mysociety/writetothem/pull/342 is ready for a developer to get involved now.

**Comment by MyfanwyNixon** [comment]
Hi @struan ,

I've looked at the copy for all these now - see https://docs.google.com/document/d/1QgnHxCsg1jpn9WN8GXdIYFHGB0pMRdVMJxzfXCFpEUI/edit#

Zarino: I've based these on the latest version of what we have in place, but also adopted many of your ideas for wording so that they're a bit more succinct. Plus I tried to fold in some of the ticketed issues with these mails that have come via user support. 

Comments still welcome of course! I think writing the copy for these emails is always tricky, and often you don't see the gaping holes until users email yo to vent their confusion and anger. Funtimes.

**Comment by struan** [comment]
I've done the confirmation page which now looks like this:

https://litmus.com/checklist/public/51240d5

The address etc is currently right aligned because making it left aligned is likely to be tricky. I can probably work out how to wrap all those bits in a something so we can left align them but I can't say how easy it would be to make that happen reliably across email clients - @zarino ?
