### ISSUE TITLE
Responsiveness infographic for easy tweeting

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#167]
To tie in with https://docs.google.com/document/d/1UmvuRmqTQd0E-lLGvKK0_AdpmyM0PLHax4ypn8FJsZs/edit, one or more infographics about MP responsiveness, to tweet.

**Comment by MyfanwyNixon** [comment]
Re-discussing this for the 2015-16 data.
Nick is going to run an early version of the data so that we can pull the headline findings out. This should give time to do some preliminary design, which can then be tweaked with the final figures before publication.

Some initial thoughts:
- How new MPs compare compared to old ones
- How pro/anto -Brexit MPs compare

**Comment by zarino** [comment]
From @MyfanwyNixon in IRC:

> the aim is to put out something tweetable, to spread the word

> the most important thing is that it grabs people's attention, gives them something they think ' that's worth sharing, I didn't know that'

I asked:

> is one single infographic most useful to you, or a series of twitter-image-card-sized pictures with maybe one big fact and statistic on each?

> (depends whether you're wanting to lead people through a story or a process, or whether you just want a visual way of presenting a linkbait headline that people then follow)

And @MyfanwyNixon said:

> yes, as I typed I was thinking probably the latter – but they could all link to a master one I guess

**Comment by zarino** [comment]
Here!

https://drive.google.com/a/mysociety.org/folderview?id=0B_2LN3vVyLmAY0NHQVp1eVdYMTQ&usp=sharing

(mySociety login required)
