### ISSUE TITLE
Use a fax gateway instead of a box in a cupboard (or just don't bother)

### ISSUE THREAD

**Issue by Flupsy** [mysociety/writetothem#176]
If we're going to support faxing then we should start using a proper fax gateway instead of relying in a box in someone's cupboard... or just don't send faxes any more.

**Comment by Flupsy** [comment]
Just got this from Keith:

At some point I'm going to move away from Virgin probably. So not sure
what that means for the fax server. Probably worth getting another one
in place anyway. I think Louise made it so two can co-exist.

So it looks like we'll have to find some alternative to using the fax server sometime soon.

**Comment by Flupsy** [comment]
The fax server has now gone away permanently.

**Comment by jacksonj04** [comment]
Presumably this should be bumped up the priority list, either pulling fax altogether or moving to a gateway?

**Comment by dracos** [comment]
There aren't really that many users of fax any more, think they can probably in the main be dealt with as they arise.
