### ISSUE TITLE
User request: better contrast on site

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#199]
"I got on your website today via an email asking if my MP had responded.

Parts of the text were a pale, pale blue against a white sheet
background.  Unfortunately, this meant eyestrain which led to a
migrane.

On a personal level, I have the Firefox add-on, Stylish, which allows
me to change colours, font sizes, remove un-necessary parts of a page
etc...and I shall be doing this very thing for your website tomorrow.

Unfortunately, not everyone knows about this (and not everyone uses
Firefox).  If pale, pale blue against a white sheet background causes
me problems, it will for others as well.  May I suggest a colour
scheme that is much easier on he eyes, or at least an option of
choosing from, say 3 or 4, for those who have the same difficulty as
myself, as well as for those that are partially sighted and may need,
say, larger text (again, Firefox is the only mainstream browser that
supports "Text Zoom Only", meaning you can enlarge text on a webpage
without having to scroll across."

**Comment by wrightmartin** [comment]
This should probably be a high priority fix, but quite simple hopefully if it's just a Sass variable to change

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/writetothem/pull/221 – I haven't tested it properly yet though.

**Comment by zarino** [comment]
I've deployed this on my vhost and it looks good. Also WCAG AA compliant.

**Before:**

![before](https://cloud.githubusercontent.com/assets/739624/5701977/4e63de1c-9a4b-11e4-97e8-7735ed76e6a3.png)

**After:**

![after](https://cloud.githubusercontent.com/assets/739624/5701980/5841217e-9a4b-11e4-985d-f33dc42d8dba.png)

**Comment by wrightmartin** [comment]
@MyfanwyNixon as we did this super quick as a user request is it pertinent to let them know once it's live?

**Comment by MyfanwyNixon** [comment]
Hey, that's still pretty quick, compared to some tickets :) I'll let 'em know.
