### ISSUE TITLE
Formatting bug - quotation marks

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#204]
User comment: "I noticed today that there appears to be a formatting error in generating some of the pages on your web site.  The first indication of this is when I click "Happy to send".  The letter comes back with all words separated by two single quotes instead of a space.  It also happens on other pages.  It doesn't appear to affect the text inserted into my confirmation e-mail and hopefully it doesn't get reflected in the e-mail to the politician."

I have two screenshots - ask if you'd like me to forward them.

**Comment by dracos** [comment]
Closing as not repeated/unfound.

**Comment by MyfanwyNixon** [comment]
> When I preview my letter to my MP it looks fine, but then when I get to the stage where it's ready to send it is peppered with  " (ie: double-quotation marks"). In fact, looking at this page they appear to be all over the place.

**Comment by MyfanwyNixon** [comment]
Follow-up:
> The issue I reported occurred in, you guessed it: Chrome and Windows 7. I just opened the same page in Internet Explorer 9 and it's all fine and dandy.

(I've asked for a screenshot)

**Comment by MyfanwyNixon** [comment]
>I'm sure your developers will be able to fix it, but I've seen things a little bit like this before: I think that {shift}{2} produces different  things depending on which version of ASCII you've set the keyboard to. . .

![writetothemscreenshot](https://cloud.githubusercontent.com/assets/944656/11392503/1efd3028-9352-11e5-995c-af51125cd2a8.JPG)

**Comment by dracos** [comment]
I have not a clue, sorry. They are just spaces in the HTML, completely bog standard. I see that some spaces on the page appear okay (e.g. the buttons, the breadcrumbs). Different font, but that font is used on previous pages presumably without any issue (as they haven't mentioned it at a previous step).

**Comment by dracos** [comment]
Actually, I have replicated it in Chrome 28 on Windows 7 at previous steps (thanks users! "first indication", sigh).

**Comment by dracos** [comment]
This was Chrome bug https://code.google.com/p/chromium/issues/detail?id=153768 present in Chromes 22-28 and fixed in Chrome 29. Chrome 29 was released in August 2013. I don't see what we can do to work around an old browser bug.

**Comment by MyfanwyNixon** [comment]
Useful to know - at least now we have something we can tell users, thanks.

**Comment by dracos** [comment]
Have added a workaround it in 1dee2b9 by disabling a style in Window Chromes 22-28.
