### ISSUE TITLE
Difficulty with sign-off

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#208]
My reading of this is that the user didn't understand that you must type a name under the 'Yours sincerely' sign-off. TBH this has caught me out in the past, so I can see it's not immediately obvious. Although - she says she them deleted 'yours sincerely' which I've just tried myself and had no problem, so maybe she;s right and there is a wider fault?

"The difficulty in sending this email was down to the fact it was asking me to not end the email with 'yours sincerley' so i deleted it and just put my name at the bottom . Following this it just kept reverting to the same error. I tried using lower case and also not using capital letters at the start of my name  but it still wouldn't send. I use windows chrome and wondered if that would have any bearing as well . "

**Comment by abimysoc** [comment]
Closing this, but leaving a pointer to #63.
