### ISSUE TITLE
User request: Underline reps' names to show they are links

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#223]
"We are using your website to encourage members and supporters to lobby their
     representatives.

     We recently had a call to our members to use
     www.writetothem.com to contact their MPs and someone had an
     issue while using Internet Explorer.

     When you type the postcode in you get a list with 3 columns.
     One is type of representatives - Cllr, MSP etc. The middle one
     is with the name of the representatives for your area and the
     last one is with voting records.

     Our supporter was confused by the fact that the text on the
     last column was underlined (See voting record) and the column
     in the middle and the name of the MP was not underlined. That
     gave her the impression that the only link to follow and write
     the message is the underlined one with the voting record. She
     spent quite a while to get to the right link because of this
     underlined and not underlined issue. This is not happening on
     my browser - Chrome.

     I realise this is a trivial request, but I am sure some users
     might appreciate the change, particularly elderly users."

Browser mentioned is IE. I use Firefox, and the underline appears on mouseover.

**Comment by dracos** [comment]
I agree; in e.g Safari links are all underlined apart from the names you want people to click on.

**Comment by wrightmartin** [comment]
![screen shot 2015-06-16 at 12 20 50](https://cloud.githubusercontent.com/assets/2292925/8181939/27c6ca0c-1422-11e5-8210-9f59998d6378.png)

Yep, no underline on the links, but underline on hover. Needs a quick fix

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/writetothem/pull/253
