### ISSUE TITLE
if the 'a' parameter is 'council', 'regionalmp' or 'mep', "Write to a Lord" is still shown

### ISSUE THREAD

**Issue by mhl** [mysociety/writetothem#224]
As reported by a campaign using the [link to us](https://www.writetothem.com/about-linktous) form, if you specify a particular type of representative then the "Write to a Lord" section is still shown under the list of representatives of the type you asked for. (Except for MPs, where since there's no choice so you go straight to the authoring page.)

**Comment by dracos** [comment]
Fixed in 5b3d317fdf7ef952780e35dc4d0384c61de17011
