### ISSUE TITLE
Add physical address and opt-in/opt-out instructions

### ISSUE THREAD

**Issue by Flupsy** [mysociety/writetothem#227]
Please add

 - [x] a physical address to the 'contact' page
 - [x] opt-out (i.e. unsubscribe) instructions to the 'privacy' page.

This is for Returnpath certification.

**Comment by mhl** [comment]
I've added the address in 690611e74bbfa307adf12ddcd00cc6c9bd29c4e8

**Comment by Flupsy** [comment]
Any chance the opt-out/unsubscribe instructions could be added soon?  Returnpath has suspended the address because it's still missing.

**Comment by mhl** [comment]
@Flupsy I've made a pull request https://github.com/mysociety/writetothem/pull/234 - will that do?

**Comment by Flupsy** [comment]
Super, thank you :)
