### ISSUE TITLE
Make help page more prominent (and maybe rename)

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#233]
"[Help](https://www.writetothem.com/about-qa)" is a tiny link at the [foot of the homepage](https://www.writetothem.com/) and every internal page. It probably isn't being found by the sort of people who write to me and say 'who are you and why are you in charge of writing to MPs?'.

I wonder whether it might be renamed, as well. It's a bit of a catch-all at the moment, but as well as help, it's FAQs and About. Possibly a case for splitting these up and giving them a page (and therefore a link) each?

**Comment by jacksonj04** [comment]
:+1:, the help pages on WTT seemed a bit rambling when we did the redesign.

**Comment by MyfanwyNixon** [comment]
Influx of emails to hello@mysociety post-election supports the theory that the Help page is hard to discover.

**Comment by zarino** [comment]
That's quite a long list of FAQs! @MyfanwyNixon do you have any inkling as to which are the most common questions people have?

**Comment by MyfanwyNixon** [comment]
Yes, I do: they're the ones I have canned replies for in user support.

 *  Are you an official service? (well, they don't phrase it like that, they just write to us as if we are the MP/councillors) https://www.writetothem.com/about-qa#govt 
 *  I didn't receive a response, what now? https://www.writetothem.com/about-qa#noreply
 *  I got a reply but it's rubbish https://www.writetothem.com/about-qa#unsatis
 *  I want to write to an MP who isn't my own https://www.writetothem.com/about-qa#onlyrep
 *  The confirmation email hasn't arrived (usually because it's in spam) https://www.writetothem.com/about-qa#noconf
 *  The questionnaire isn't suitable for my special circumstances  https://www.writetothem.com/about-qa#unsuitable
 *  I wrote a message but I don't want to send it https://www.writetothem.com/about-qa#cancelmsg
 *  I want a copy of my message https://www.writetothem.com/about-qa#copymsg
 *  How long does it take to receive a reply https://www.writetothem.com/about-qa#longwait
 *  Please stop sending me emails https://www.writetothem.com/about-qa#stop
 *  Did my message reach my rep? https://www.writetothem.com/about-qa#know
 *   My postcode brings up the wrong representatives  https://www.writetothem.com/about-qa#wrongreps
 *  Why can't I send multiple identical letters? https://www.writetothem.com/about-qa#formletters

**Comment by jacksonj04** [comment]
It might be worth adding something like Screentime to see how much time people actually spend with various FAQs on screen.

**Comment by abimysoc** [comment]
The hypothesis is that they can't even find the FAQs. Let's keep the focus narrow here and sort that out first.

**Comment by zarino** [comment]
@abimysoc – You're right, minimal change is to put the Help link in the top right corner, next to the mySociety tab

![screen shot 2015-06-02 at 10 06 45](https://cloud.githubusercontent.com/assets/739624/7932373/bf3dc462-090f-11e5-96d1-e5de23dfe30e.png)

@jacksonj04 – Screen time tracking, or click event tracking for the table of contents at the top? Or both?

**Comment by MyfanwyNixon** [comment]
Would it be there on all the internal pages too? Just thinking that many people probably need help once they've started the process.

**Comment by zarino** [comment]
@MyfanwyNixon – yes, it would be at the top of all the pages.

**Comment by MyfanwyNixon** [comment]
Great, thanks!
Also worth mentioning, I think, that the FAQs page plays an important part in @abimysoc and my efforts to cut down on user support mail. 

So if we do remove any of the FAQs let's monitor whether there's any associated rise in mail.

**Comment by zarino** [comment]
@MyfanwyNixon – I think it'll more likely be a case of making the most common questions more prominent, and the less common ones less prominent, rather than completely removing any of them.

It's counter productive to make people scroll through a list of 50 "frequently" asked questions, when we *actually* know which ones are the most frequently asked, and could present them more prominently so people can find them quicker.

But as @abimysoc says – before all that, we need to make sure people are reaching the FAQ page in the first place.

**Comment by MyfanwyNixon** [comment]
Yup, that sounds good.

**Comment by abimysoc** [comment]
Small usability thing: I do loathe target="_blank", but I think there's a case for it here. If someone's halfway through writing a message, thinks "I need help" and clicks the help link, we don't want them to lose their message (because #13) by navigating away from the page.

**Comment by dracos** [comment]
The help could open in a floating div over the page to prevent that situation and not have a potentially confusing new window. I thought we actually used that technique somewhere - ah yes, on write pages we do exactly that with the sidebar links though it was broken due to a combination of it getting dropped in the redesign and some badly written A/B JavaScript, now fixed. Could look a bit better, but I think that's potentially nicer than new page.

**Comment by zarino** [comment]
Pull request here – https://github.com/mysociety/writetothem/compare/issues/233-help-link – adds a help link to the top right. It opens in a blank window. Before we get clever about javascript modals or inline help, let's see whether this change alone decreases support emails.
