### ISSUE TITLE
Explanation of dissolution

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#239]
On the 'choose your rep' page it currently says:
"There’s an upcoming election. We’ll be adding your new representative as soon as we can after the election."

It would be good to expound on this with a link to some more explanation, even if it was just to http://www.parliament.uk/get-involved/contact-your-mp/contacting-your-mp/

**Comment by MyfanwyNixon** [comment]
Some messages from users:
> Why can't I contact Gerald Kaufmann.  The option "Your MP" displays with strikeout formatting and the page informs me there's an upcoming election (thanks for that).
and:
> Really? The United Kingdom no longer has a government?  My MP is, supposedly, a member of the UK government. And he's  quit, has he?  [...] Quit giving them a break.
and:
> There seems to be a gaping hole now that parliament is dissolved. Surely until another MP is elected the current one should be able to assist his or her electors?

**Comment by MyfanwyNixon** [comment]
Here's a follow-up comment:

> It may sound ignorant but I wasn't even aware parliament had dissolved already - who's in charge now!  Hence I'd (wrongly and hastily) assumed it was your decision to suspend the service for the time being.

> Maybe the text on the website could be something like - "Parliament has now been dissolved so you don't officially have an MP until after the election.  Parliamentary contact details will not work until that time."

**Comment by MyfanwyNixon** [comment]
(This one via TWFY support):

> I would like to know who is now my MP as Kevin Barron left 30 March 2015

**Comment by dracos** [comment]
Text expanded

**Comment by MyfanwyNixon** [comment]
Thanks!
