### ISSUE TITLE
Cursor: default means we don't get an I-beam over text

### ISSUE THREAD

**Issue by owenblacker** [mysociety/writetothem#242]
Is there a particular reason that `wtt.css` sets `cursor: default` at the level of `body`?

Hovering over the text in the [zeitgeist page](https://www.writetothem.com/stats/2014/zeitgeist) and I get a pointer, rather than an I-beam (in Chrome 41.0.2272.118 m (64-bit) on Windows 7 Pro, build 7601 SP1).

It just struck me as odd…

**Comment by zarino** [comment]
This is coming from Foundation 4. It looks like the `cursor: default` behaviour was [removed in August 2014](https://github.com/zurb/foundation/pull/5638), but the latest version of the zurb-foundation gem is from [September 2013](https://rubygems.org/gems/zurb-foundation/), a year earlier.

@dracos – what do you suggest? Do we just override the `cursor: default` with our own `body { cursor: auto }`? Or upgrade Foundation somehow?

**Comment by zarino** [comment]
Ok, for now we'll just set `$cursor-default-value: auto`.
