### ISSUE TITLE
Email to MEP being marked as spam

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#248]
Eg Message id 1d4d8374af338cd45ae1

The bounce email says:
Our system has detected that this message is likely unsolicited mail. To reduce the amount of spam sent to Gmail, this message has been blocked. Please visit http://support.google.com/mail/bin/answer.py?hl=en&answer=188131 for more information.

Looks like three previous emails to this MEP have also bounced. The user's email does not appear all that spammy to me.

Is this a question for @Flupsy or maybe @dracos ?

**Comment by Flupsy** [comment]
The message did leave on the Returnpath-certified route, so I wouldn't expect this.  Maybe the MEP has accidentally (or deliberately!) marked our messages as spam in the past.

Google doesn't have a feedback loop for senders unfortunately...

**Comment by dracos** [comment]
Closing
