### ISSUE TITLE
Not obvious MP's name is a link?

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#266]
>   When I input my postcode 'BS23 3PE', the only option I can click for my MP is to see his voting record, there is not a link to contact him.

As far as I can see, this user has missed the fact that the MP's name is actually a link. 

It's a fair point that the other links on the page tell you what will happen ("see this MP's voting record" etc) - we could consider changing the wording to "Write to [NAME]". Although it does say 'choose your representative' at the top of the page.

**Comment by dracos** [comment]
Might have been dealt with by #253 which might not have gone live, not sure.
