### ISSUE TITLE
User issue: capital/lower case defaults

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#269]
> in the data form, in the mobile version I have just used, there is inconsistency in default case for letters:
> Email address defaults to initial capital - which is weird and led to me having a discrepancy. 
> Postcode does not default to All Capitals, which is a bore. 

Don't know if there's anything we can do about that?

**Comment by dracos** [comment]
Doesn't matter what case they use for postcode; email is dupe of #256.

**Comment by zarino** [comment]
I think we can make the postcode input *look* like it's all in capitals by giving it:

```
input#pc {
    text-transform: uppercase;
}
```

In reality, the contents of the text input will still be lowercase, but they'll *look* to the user like they're uppercase.

**Comment by dracos** [comment]
Thanks for the idea, @zarino!
