### ISSUE TITLE
User request: Lords responsiveness table

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#271]
> I think its important that you list Lords that do not reply to emails or any contact for that matter. Sadly I get told often that the public get little response from Lords members. This is sad and I must say iv tried through your system and had the same issue. 
> 
> Im glad you are making statistics of this and I am aware that they do not have to reply.

**Comment by MyfanwyNixon** [comment]
Lords are not obligated to respond to correspondence, but we agree that this could be an interesting dataset. Nick says it shouldn't be substantially trickier than running the MP data and we can use the same design etc as that existing pages.

We decided to publish it at some point in the future, but at a different time to the MP table, so we can give it the attention it deserves.

**Comment by jacksonj04** [comment]
Pre-emptively closing this, as current plan is to move away from individual MPs (and Lords) in tables, and towards slicing and dicing based on party, cohort, etc
