### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#276]
writetothem/templates/website/corrections-thanks.html

includes a link to https://www.mysociety.org/helpus
Should go to https://www.mysociety.org/about/get-involved/

**Comment by dracos** [comment]
In case anyone else linked to that page, this should first be fixed at the mysociety.org end to redirect (I remember that being done though, hmm).

**Comment by abimysoc** [comment]
/helpus/ was definitely on my list of pages that were supposed to be redirected when we did the mysociety.org redesign, yup. Bit worrying if they weren't all done / have been reverted. [Full list here.](https://docs.google.com/spreadsheets/d/1Hf-_fUxnUSPgnwju6vLNeu25DlZUSQO8Up3c7--QMYI/edit#gid=7)

**Comment by dracos** [comment]
It's the final slash difference; should be fixed now at mysociety.org end.

**Comment by dracos** [comment]
Fixed this link at WTT end along with some other aboutmyvote etc links that I spotted were broken.
