### ISSUE TITLE
Reduce front page weight

### ISSUE THREAD

**Issue by dracos** [mysociety/writetothem#279]
The front page is currently about c. 325K.
Over half of this (174K) is the JPEG image (2048x864 at any browser size). Other images are c. 6K, the page is 6.6K, fonts are 50K, JavaScript is c. 65K, CSS 21.5K.
#278 gets the main CSS down to 8.5K and removes 10K of JavaScript, but I think a bit of work on the main image could save the most, on mobile if not everywhere.

**Comment by jacksonj04** [comment]
Quick point on the image if we use any compressing tools, the photographer gave us the OK to use it as long as the EXIF copyright tag remained intact.

**Comment by dracos** [comment]
The front page is now 155K (>50% reduction) at narrow width (210K, 35% reduction wider), yay :)
Next steps would be perhaps not having fonts at narrow width (in the absence of knowing "low bandwidth"), and dropping jQuery.
