### ISSUE TITLE
User issue: form submission does not work in Microsoft Edge

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#286]
>  I'm sure you are aware but the "Write your message" form  (www.writetothem.com/write) doesn't work on the Microsoft Edge browser (Win 10 64bit - Edge build 20.10240.16384.0) for some reason. Despite having a message in the box, on clicking  "preview and send" it shows an error message of "Please enter  your message" in red at the top.

**Comment by dracos** [comment]
I’ve just tried the process in Edge, precisely the same version, 20.10240.16384.0, and it’s fine.
