### ISSUE TITLE
'Donate' banner

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#290]
As suggested by @markcridge:
Can we display a banner across the top of the site, from Monday to Weds next week, and linking to https://www.mysociety.org/donate/

> Help us make websites that empower people. Your donations support sites like this.

**Comment by MyfanwyNixon** [comment]
Assigning @dracos but please change if there's someone more appropriate.

**Comment by dracos** [comment]
The only banner WTT can currently do looks like this http://matthew.writetothem.dev.mysociety.org ; would need design input unless you want me to just use that, or pick a different colour.

**Comment by MyfanwyNixon** [comment]
That's fine, thanks - the other sites will be quite plain too.

**Comment by dracos** [comment]
`290-banner` branch has it ready.

**Comment by lizconlan** [comment]
banner up

**Comment by MyfanwyNixon** [comment]
Bit squished on my browser, Firefox (the top margin of this image is the line of my browser menu bar):

![squished](https://cloud.githubusercontent.com/assets/944656/11927893/91d2f072-a7c7-11e5-83e6-71499207376b.jpg)

Could we include a line break or two before the text? Might also make the message more visible.

**Comment by dracos** [comment]
Old CSS cached; #291 to deal with that; is fine now.

**Comment by MyfanwyNixon** [comment]
Also one to re-instigate for Xmas 2016? Thought it could run from 16 December to 2 January this year.  Maybe substitute "mySociety" for "us" this time, to give a little foretaste of the fact they'll be taken to a different site?

**Comment by mhl** [comment]
This is deployed for 2016 now

**Comment by mhl** [comment]
Oops, although I forgot to change the "us" to "mySociety"...

**Comment by mhl** [comment]
Fixed now

**Comment by MyfanwyNixon** [comment]
This banner can come down now - thanks!
