### ISSUE TITLE
Possible bug: Feedback page

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/writetothem#292]
Message from user:

Hi there. I've found a bug on the site. When responding to "Did they reply" emails I see the first page but when I click to answer whether this is the first time I'vecontacted an MP it shows an error. 

See screenshots: http://cl.ly/e9dC

**Comment by Gemmamysoc** [comment]
Another user's feedback today too:

I received an e-mail from you asking if my MP had replied to an enquiry I made regarding [  ]. When I opened the link there was a question asking if I had contacted people before but when I answer it tells me there is a problem and to try later.

**Comment by dracos** [comment]
mastodon hosts survey.mysociety.org which WTT can sometimes use for an extended survey, and that's currently down, so it can't decide if it's already shown the survey before. I've disabled this for the moment.

**Comment by dracos** [comment]
Their answer was recorded, so just say sorry for the error received.

**Comment by Gemmamysoc** [comment]
Okay, thanks!
