### ISSUE TITLE
Placeholder text on 2015 responsiveness table page

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#296]
Could we place some copy on https://www.writetothem.com/stats/2015/zeitgeist, thus:

> Due to last year's General Election, we'll be publishing the next WriteToThem responsiveness data table in mid-2016.

> This will ensure a level playing field, as all MPs will have been in position for a full year. 

> If you'd like to know when it goes live, [subscribe to the mySociety newsletter](https://www.mysociety.org/subscribe/), [follow our blog](https://www.mysociety.org/blog/) or add us on [Twitter](https://twitter.com/mysociety) or [Facebook](https://www.facebook.com/mySociety/).

**Comment by abimysoc** [comment]
2016 page should have something as well, probably, or redirect. 

Question: are we going to promote these stats as '2015' or '2016'?

**Comment by MyfanwyNixon** [comment]
Or 2015-16.

**Comment by abimysoc** [comment]
@MyfanwyNixon I delegate it to the communications manager to make a decision.

**Comment by MyfanwyNixon** [comment]
2015-16 seems clearest to me.
