### ISSUE TITLE
Wording of second confirmation email possibly misleading

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#299]
>  I confirmed via your email to me & the link. Now I get an email from you asking me to repeat this last step as "perhaps the email got lost". I don't want to annoy them with a duplicate! Should I go ahead & repeat anyway?

It may be this user's individual circumstances that have caused the confusion: he thinks he clicked the confirmation link in the first email, but according to our system, he didn't.

So he has read 'perhaps the email got lost' as meaning his email to his reps has possibly been lost. One for me to have a look at.

**Comment by MyfanwyNixon** [comment]
https://github.com/mysociety/writetothem/blob/884e226a44f1a0e540990319db200e01d5f153c7/templates/emails/confirm-reminder and https://github.com/mysociety/writetothem/blob/884e226a44f1a0e540990319db200e01d5f153c7/templates/emails/confirm-reminder-group

I suggest that we change the wording.

Change:
> (This is a reminder email; perhaps the first one got lost?)

To: 
> This is a second and final confirmation mail from WriteToThem. You have not yet clicked the confirmation link, so your email to <?=$values['recipient_name']?> has not yet been sent.

> Please click on the link below to confirm your message.

While I'm looking at this text, I think we could remove:

> If for some reason we can't send your message or it doesn't get through, we will email you a copy of
your message so you can contact your <?=$values['recipient_name']?> by more traditional, albeit less fun, means.

and change:

> If you did not request that a message be sent to <?=$values['recipient_position_plural']?>, please let us know by sending an email to <?=$values['contact_email']?>

> Don't worry; nothing will be sent without your permission.

to:

> If you do not wish to send this message, please ignore this email. Your message will remain unsent; subsequently it will be wiped off our servers.

**Comment by dracos** [comment]
Go for it!

**Comment by dracos** [comment]
Not closed until it's merged/deployed :)
