### ISSUE TITLE
Add Adwords conversion tracking code

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#301]
See https://github.com/mysociety/Non-Site-Specific/issues/687

As a condition of the higher level Google Adwords grant, we need to be tracking at least one goal. The sooner we can get this in place, the sooner I can reapply and the sooner we'll get more users back!

@jacksonj04 says:

> https://support.google.com/adwords/answer/6095821 is the guide on doing it.

> Basically, on each site, on each page which counts as a 'conversion' (eg the WTT success page, the WDTK success page, the TWFY postcode search result page, the FMS success page) we add a bit of code which tells AdWords "whatever you did, worked". When AdWords spots an incoming "success" message, it records that against the relevant ad (assuming the user arrived on the site via an ad) as a conversion.

For WTT, yes, the 'your message is on its way' page seems like the obvious target.

**Comment by MyfanwyNixon** [comment]
Can I bump this please? Be great to get this sorted so I can reapply for the higher tier Google Grant.

**Comment by MyfanwyNixon** [comment]
Tracking is now in place.
@jacksonj04 please could you record for posterity what exactly we are tracking? Is it clicks from the confirmation email?

NB This was primarily a box-ticking exercise for us, so that we could regain the higher tier Google grant. However now that the tracking is in place, I can see its utility.

Currently, the figures are not encouraging. For the last month:

Total clicks from ads: 7,504
Total conversions: 12
Conversion rate: 0.16%
Cost per conversion: $511.08 !

Some initial thoughts:
- Can we compare these with completion results for the site as a whole?
- Can we find out where exactly people are dropping out?
- Adwords allows me to see which keywords are getting the most clicks and the fewest conversions - currently 'councillors' (aha and of course half the country can't contact their councillors at the moment because the post-election data isn't in place yet - maybe this needs reassessing in a couple of months).

**Comment by jacksonj04** [comment]
We are tracking the number of people who, after clicking an Adwords ad (that's on Google search and Adwords ad banners around the web), then go on to visit the confirmation page (which is a proxy indication of a message being sent). In other words, "how many people clicked an advert then sent a message".

**Comment by MyfanwyNixon** [comment]
Thanks Nick! Yep, that makes sense. Conversion does seem very low but presumably the post-election lack of councillors is skewing it.
