### ISSUE TITLE
Broken link to aboutmyvote on “What postcode should I use?”

### ISSUE THREAD

**Issue by andylolz** [mysociety/writetothem#303]
[How to register to vote](http://www.aboutmyvote.co.uk/register-to-vote/how-to-register-to-vote) (linked to from the [“no fixed abode” bit of the What postcode should I use? page](https://www.writetothem.com/about-constituency#loccon)) currently looks like this:
![screen shot 2016-04-07 at 14 27 40](https://cloud.githubusercontent.com/assets/464193/14352555/05a1d3e2-fccd-11e5-9376-9f8527d0a2c5.png)

I think it _should_ link to this:
http://www.aboutmyvote.co.uk/register-to-vote/registering-to-vote-with-no-fixed-address

**Comment by andylolz** [comment]
I guess the site needs to be deployed before this fix works.

**Comment by dracos** [comment]
Yep, and didn't get round to it on Friday - now there :)

**Comment by andylolz** [comment]
Ace – thanks!
