### ISSUE TITLE
Donate call to action

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#306]
Moving across to individual repos from mysociety/sysadmin#679

Primarily a design issue: latest suggestion from @zarino  is a test where we display donation links only at each site’s pleasure points:

-     Work out where the pleasure points are in the user flows for our products (I think @MyfanwyNixon did some research on this before?) and put donation links there, with Analytics tracking IDs.
-     Make the donation links really persuasive. Think Save The Children or RSPCA level heart-tugging. Get crying children on there. Again, all-out, no shame.
-     Put them up for exactly 2 months, as before.
-     See whether donations rise.

**Comment by MyfanwyNixon** [comment]
Heavy usage of WTT at the moment so it's been suggested we prioritise the call to donate at the 'submitted' page.

**Comment by JenMysoc** [comment]
To clarify this should be on the page people see once they've clicked the email link to submit their message (looks like this: https://www.writetothem.com/confirm?token=vemd3oifwp_s6u7keh5vblpusqys32)

**Comment by struan** [comment]
There is already a donate button on that page below the fold which I will hide for this case as two is weird.

My rudimentary design skills will result in this:

![screen shot 2016-06-29 at 15 38 11](https://cloud.githubusercontent.com/assets/5310/16456388/9a6e54b8-3e0f-11e6-8506-0f6e11c2d6ec.png)

which isn't elegant but is obvious. Improvements w

**Comment by JenMysoc** [comment]
This definitely makes it far more prominent so that's good! @MyfanwyNixon @markcridge @paullenz thoughts?

**Comment by MyfanwyNixon** [comment]
Happy - though maybe the button above the donate text, just to differentiate it from the paragraph above?

**Comment by struan** [comment]
With the button above it looks like:

![screen shot 2016-06-29 at 16 30 40](https://cloud.githubusercontent.com/assets/5310/16458416/e3ac2b9e-3e16-11e6-9d8c-8708b190156f.png)

**Comment by MyfanwyNixon** [comment]
:+1: Looks good to me
