### ISSUE TITLE
Development environment

### ISSUE THREAD

**Issue by zarino** [mysociety/writetothem#309]
Most of our sites have a vagrantfile and provisioning script.

WriteToThem has some instructions about `gem install` steps you’re meant to manually run, but it just assumes you set up all the other dependencies (PHP, Apache?) yourself.

It would be nice if there was just a simple, standard way of getting this running locally. Maybe a vagrant machine is overkill, maybe not. But it's what all of our other sites use.

---

As it happens, I've worked out that, to get it running on my Mac, I just needed to run https://github.com/zarino/micropache inside the `/web` directory.

I also needed to set `writetothem.local` as an alias for `127.0.0.1` in my `/etc/hosts` file, to avoid an exception from `/phplib/fyi.php:44` when it assumes there will be a dot in `$_SERVER['HTTP_HOST']` (which, if you’re just using `localhost:8000`, there won’t be).

I have no idea whether this set-up is sufficient to have everything working in WriteToThem, but it's enough for me to make changes to the templates and styling.

**Comment by sagepe** [comment]
I'm going to close this https://github.com/mysociety/writetothem/pull/489 updated the development environment last year.
