### ISSUE TITLE
Use HTML for Questionnaire emails

### ISSUE THREAD

**Issue by struan** [mysociety/writetothem#315]
It'd be good to make the questionnaire emails better laid out so it's less a wall of text with links. To do this we need to send HTML emails.

**Comment by abimysoc** [comment]
Some design ideas for the emails exist in the comments to #164 (which is a more general ticket about HTML emails sitewide, not just the questionnaire ones).

**Comment by MyfanwyNixon** [comment]
User comment:

> I submitted a letter to go to my MEPs yesterday via what looked like a proper site and now I receive an email asking me to click a rather strange link.  I am very confused.
>  
> Please reply to this email, confirming that this is legitimate. 
>  
> I cannot understand why there is a further block and distancing between a normal citizen such as me and my representatives in the European Parliament.

**Comment by abimysoc** [comment]
Resolved by #342, I believe.
