### ISSUE TITLE
Spam in WTT and TWFY user support inboxes

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#331]
Typically the inbox is full of twenty or thirty spam mails each day. @abimysoc informs me that this isn't an issue with the FMS inbox so perhaps something has been implemented there that can be copied?

![spam](https://cloud.githubusercontent.com/assets/944656/16561673/52222824-41f2-11e6-8c36-261b11fa1029.jpg)

At the moment they all follow a similar format (intended-to-be-enticing sentence followed by link) and so are probably coming from the same source:

![spam format](https://cloud.githubusercontent.com/assets/944656/16561783/ee30dab2-41f2-11e6-9560-a23447708e61.jpg)

**Comment by MyfanwyNixon** [comment]
Even more than usual today - still following the same general format.

![fireshot screen capture 774 - inbox 65 - writetothemsupport mysociety_org - mysociety mail - mail_google_com_mail_b_86_u_0_ inbox](https://cloud.githubusercontent.com/assets/944656/16724609/7b387fa2-474b-11e6-834a-0fa6196e4a48.jpg)

**Comment by hazelesque** [comment]
@MyfanwyNixon *nod*

**Comment by abimysoc** [comment]
Closing as being handled elsewhere.
