### ISSUE TITLE
Users complaining that the link is restarting the message-writing process

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#338]
There have been a couple of similar messages in past 24 hours.

>I wrote an e mail letter to Rachell and was e mailed to ask me to click on a website address, which I did.There, I was asked my postcode, which I typed in and pressed 'go' expecting to see a message telling me my letter had been despatched but that did not happen.

>Can you tell me if my letter is in the process of being delivered?

and

> I wrote a letter to my MP through your site.  I got a reply back asking me to confirm via link.  Having clicked on the link it took me to a page that restarts the whole process again and asks for donations.

>This is unprofessional and confusing!  Either you have passed on the letter or you haven't.  If so confirm it if not why not?  Maybe your a case for investigation and complain. I will assess whether I want to donate or not.

**Comment by MyfanwyNixon** [comment]
> I did click the confirmation button several times. The link you have given now does not show a confirmation button just a donate one.

**Comment by MyfanwyNixon** [comment]
@zarino there are a few mentions of people seeing nothing but the donate button in the above complaints - is there any way that your recent work could have broken anything?

**Comment by MyfanwyNixon** [comment]
> I have clicked on the links to confirm  I want my email sent but am not sure it has worked

**Comment by MyfanwyNixon** [comment]
I think this mail might have hit the nail on the head:

>   On the confirmation email, it starts by saying to 'click on the
     link below' to send your message.  Depending on the screen size
     being used, the first link (the one to the writetothem.com
     homepage) could be seen to be the one to click.

However, once we introduce html emails presumably this ticket will no longer be an issue.

**Comment by dracos** [comment]
No reason not to change `WriteToThem.com` to `WriteToThem` in the text parts of those emails, though, done!
