### ISSUE TITLE
Within the Help section, provide a wireframe/template for writing to your MP

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#339]
Idea on the back of https://twitter.com/adebradley/status/756442214247571456:

![twip1](https://cloud.githubusercontent.com/assets/944656/18008586/a023f908-6ba0-11e6-8f08-5ceb6070727a.jpg)

In the help section, include *generic* advice on things you might like to include in a letter. This is not in contravention of our 'no copy and paste emails' rule and in fact may help to strengthen it: I'm thinking more of a wireframe which would suggest sections such as:

1. The main reason you're writing
2. Why it is important to you - does it impinge your work? Your community? 
3. Any secondary reasons
4. What you hope your MP/rep will do about it

You could even link to it from the composition frame: "Not sure what to write? Here's some guidance"

Is that really patronising though? It might help some people who aren't used to writing messages like this.

https://wiki.openrightsgroup.org/wiki/Letter_writing has some nice helpful parts, from 'Magical Ws' onward.

**Comment by MyfanwyNixon** [comment]
@wrightmartin - as just discussed, I'd like some design help with the tables in this post, thanks!

The draft is here: https://blogs.mysociety.org/mysociety/?p=32417&preview=true

I don't think our default elegant table style is quite right for this post (tell me if you don't agree! It's possible I need new eyes to look at it).

You can see the standard Google docs tables in the original document: https://docs.google.com/document/d/15PGYHlNF78EJm5Dm_xyqfCnrGm1VWWsBB_nXHoTrXL0/edit#heading=h.9i4n0zvb51qj

Somehow they feel easier to parse when the sides are enclosed like that.

Option B would be to screenshot them, but I suspect there's a possibility people will want to copy and paste text from the tables, so it wouldn't be ideal.

**Comment by wrightmartin** [comment]
Argh, not as simple as I'd hoped, thanks WordPress! I'll have to put this in a PR and get it approved and deployed :) No biggy

**Comment by zarino** [comment]
We can deploy this (if it hasn't already been deployed) at the same time that we deploy https://github.com/mysociety/orgsites/pull/896

**Comment by MyfanwyNixon** [comment]
Comment from @abimysoc  ([on internal blog](https://blogs.mysociety.org/internal/2016/09/19/quick-thought/))

> I’m reminded of gov.uk’s design principles, specifically “The people who most need our services are often the people who find them hardest to use.” One of the things civic tech is about is acknowledging that there are educational and social barriers to using it, and helping to overcome them: holding people’s hands on their way through a process they find difficult.

> Royal Mail don’t give advice about how to write the letter they’re going to deliver because they can’t make tips pop up on the paper as you write. We can. (I’ve seen it happening recently with improving the “placeholder” text in the FixMyStreet reporting form fields, to help show people what to put there.) [This one](https://mojdigital.blog.gov.uk/2016/01/05/making-it-easier-for-staff-to-process-help-with-court-fees-applications/) is excellent on contextual help.

> So I really don’t think it belongs as a blog post on a separate website – support like this is part of the tool itself (and in an ideal world would be iterated several times over with real-life users giving feedback).

This probably needs to be a new ticket or several tickets!
