### ISSUE TITLE
Longer email addresses get broken

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#346]
> I didn't get a reply but it might have something to do with the link you put to my email address.  The
>  full address is xxxxxx@xxxxxxxxxxxxxxx.free-online.co.uk but  the clickable link is in the email you forwarded is xxxxxx@xxxxxxxxxxxxxxx.free-onli , leaving out the last bit,  ne.co.uk.  If Mr Clarke tried to reply using the link you  provided, I would not have received it.

This is true (supposing that the MP doesn't spot the issue and fix it manually). You can see what the email address looks like in the sent message at ID 58de82c4e34078670c9a:

![fireshot screen capture 863 - message queue - https___www_writetothem_com admin - www_writetothem_com_admin_index_php_page fyrqueue](https://cloud.githubusercontent.com/assets/944656/17848918/177fcb36-684e-11e6-896c-2b908044790f.jpg)

**Comment by dracos** [comment]
Fixed by 3ab222693989ed76801e163221c04fb1f8bcf361
