### ISSUE TITLE
Investigate Kevin Brennan MP correspondence numbers

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/writetothem#360]
We had the wrong email address for Kevin Brennan MP in 2015 and early 2016. We changed the email address on his request on 26th February 2016 but his team is now saying that this wrong email address has meant his WTT stats are wrong. 

Please can we find out how many emails were sent to his email address in 2015 ( i will confirm the date that he changed his email address)?

Please can we also find out how many emails were sent to him since Feb 2016 and how many of those have replies?

**Comment by jacksonj04** [comment]
Issue resolved with @MyfanwyNixon via IRC.
