### ISSUE TITLE
Emails being returned because of councils' email policies

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#364]
eg see message ID ec6561019b5f4b79cbd3

> SMTP error from remote mail server after RCPT TO:<memberservices@rhondda-cynon-taff.gov.uk>:
host eu-smtp-inbound-1.mimecast.com [195.130.217.211]:
550 Administrative prohibition - envelope blocked - https://community.mimecast.com/docs/DOC-1369#550

So, if I've understood correctly, they have blocked emails from the WTT domain? I've tried tweeting them (as my emails also bounced back). They were looking into it at the end of Nov but no news after that: https://twitter.com/mysociety/status/803651262566764544

**Comment by MyfanwyNixon** [comment]
Changing this ticket to be more widely about councils who automatically return our messages.

Message id fcb8b913a1326374267b:

**Comment by MyfanwyNixon** [comment]
ID 	64c5d0984c774ce31ab7
SMTP error from remote mail server after end of data:

> host chpseg01n.somerset.gov.uk [194.74.187.85]:
> 550 Header value not allowed

Are these (including the above) issues that @sagepe  would be able to/should look at?

**Comment by sagepe** [comment]
`#550 5.7.1 RESOLVER.RST.NotAuthorized; not authorized`

This is the remote server rejecting the message. This could actually be for all sorts of reasons. In this case, I wonder if it might be because [Gail Ross has resgined](http://www.johnogroat-journal.co.uk/News/Wick-Highland-councillor-Gail-Ross-resigns-22112016.htm) as a councillor so her mailbox might be embargoed or removed. (I only discovered this when searching for her email address to check it was correct!)

**Comment by MyfanwyNixon** [comment]
Ah thanks @sagepe - that could just have been me not being diligent enough on that one: normally I will click through to check that the councillor is still active. I'd certainly expect their mailboxes to be removed on resignation.

**Comment by sagepe** [comment]
I've just had a look at the logs for transactions involving `chpseg01n.somerset.gov.uk`. That host has accepted some mail from us today, so it's not a global issue, for example messages for dmitchell@somerset.gov.uk, dnyeomans@somerset.gov.uk and jcave@somerset.gov.uk were accepted.

Without a bit more information it's going to be difficult to see exactly why the message for sdcrabb@somerset.gov.uk was rejected. The error is fairly generic. Was there any more info in the bounce?

**Comment by MyfanwyNixon** [comment]
It's at ID 64c5d0984c774ce31ab7 if you have access to the WTT queue. 

Oddly enough, if it's relevant, the message was *from* a @somerset.gov.uk email address.

Return-path: <>
Envelope-to: fyr@pluto.ukcod.org.uk
Delivery-date: Thu, 23 Feb 2017 12:02:36 +0000
Received: from ocelot.ukcod.org.uk ([46.43.39.78]:42747)
by pluto.ukcod.org.uk with esmtp (Exim 4.80)
id 1cgs6W-0001m0-LM
for fyr@pluto.ukcod.org.uk; Thu, 23 Feb 2017 12:02:36 +0000
Received: from Debian-exim by ocelot.ukcod.org.uk with local (Exim 4.80)
id 1cgs6W-0007Vt-Dp
for fyr-udc2ooxlri_5uxttho4dvkeizyywfo@writetothem.com; Thu, 23 Feb 2017 12:02:36 +0000
X-Failed-Recipients: sdcrabb@somerset.gov.uk
Auto-Submitted: auto-replied
From: Mail Delivery System <Mailer-Daemon@ocelot.ukcod.org.uk>
To: fyr-udc2ooxlri_5uxttho4dvkeizyywfo@writetothem.com
Subject: Mail delivery failed: returning message to sender
Message-Id: <E1cgs6W-0007Vt-Dp@ocelot.ukcod.org.uk>
Date: Thu, 23 Feb 2017 12:02:36 +0000
X-Delivered-Suffix: -udc2ooxlri_5uxttho4dvkeizyywfo

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

sdcrabb@somerset.gov.uk
SMTP error from remote mail server after end of data:
host chpseg01n.somerset.gov.uk [194.74.187.85]:
550 Header value not allowed

Return-path: <fyr-udc2ooxlri_5uxttho4dvkeizyywfo@writetothem.com>
Received: from pluto.ukcod.org.uk ([46.43.39.71]:58684)
by ocelot.ukcod.org.uk with esmtps (TLS1.2:DHE_RSA_AES_128_CBC_SHA1:128)
(Exim 4.80)
(envelope-from <fyr-udc2ooxlri_5uxttho4dvkeizyywfo@writetothem.com>)
id 1cgrgu-00080p-WF
for sdcrabb@somerset.gov.uk; Thu, 23 Feb 2017 11:36:09 +0000
Received: from localhost ([127.0.0.1]:37687 helo=localhost.localdomain)
by pluto.ukcod.org.uk with esmtp (Exim 4.80)
(envelope-from <fyr-udc2ooxlri_5uxttho4dvkeizyywfo@writetothem.com>)
id 1cgrgu-00009x-Gi
for sdcrabb@somerset.gov.uk; Thu, 23 Feb 2017 11:36:08 +0000
Subject: Letter from your constituent Jeanette Cave
Message-ID: <c2ueadifl3_7o6xt6qzvvx75rsif3g.3e94054f@writetothem.com>
To: "Cllr Samuel Crabb" <sdcrabb@somerset.gov.uk>
Date: Thu, 23 Feb 2017 11:36:08 +0000
From: "Jeanette Cave" <jcave@somerset.gov.uk>
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

**Comment by sagepe** [comment]
My suspicion is that you've hit the nai on the head - they are rejecting external mail that has a From: header containing a somerset.gov.uk address to prevent spoofing. There's nothing else there that looks like a problem. Really we'd probably have to contact them and check to see whether this was the case to be certain.

**Comment by abimysoc** [comment]
This repository is public, so please remove people's email addresses from the comments...

As further support for this diagnosis, a recent bounce from Thurrock to a FixMyStreet report made by someone using a Thurrock email address gave the error "550 Rejected by header based Anti-Spoofing policy" and refers you to https://community.mimecast.com/docs/DOC-1369#550

**Comment by MyfanwyNixon** [comment]
Done, thanks Abi

**Comment by jacksonj04** [comment]
Relevant: #193 (which, along with referenced tickets, explores DMARC and address spoofing with no discernable outcome other than "we'll keep an eye on it").
