### ISSUE TITLE
Survey should be rewritten and replaced by surveying platform

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/writetothem#366]
Related to #75 (if only because we may as well tidy up as we go), #106 and #108.

The current demographics/attitude survey which runs for a portion of all users who answer the "did you get a response" email could do with being rewritten to better match surveying standards.

As part of this, we should do our best to move it away from our own surveys platform and on to one which is actually designed to do surveying and reporting.

**Comment by ajparsons** [comment]
This has been addressed by implementation of surveygizmo intergration https://github.com/mysociety/writetothem/pull/399
