### ISSUE TITLE
Unrecognised postcode

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#368]
>Tor Gorm Road, North Kessock IV1 3JJ

This is not recognised by MapIt/WTT, but is recognised by the Royal Mail postcode finder.

**Comment by dracos** [comment]
http://www.highland.gov.uk/meetings/meeting/3720/ross_and_cromarty_committee/attachment/70541 – it's a brand new estate. Google Maps doesn't know that road or postcode either. There's a new postcode database release this month, so hopefully it'll be in that.

**Comment by abimysoc** [comment]
Postcode is now recognised.
