### ISSUE TITLE
Political Knowledge Survey

### ISSUE THREAD

**Issue by ajparsons** [mysociety/writetothem#392]
As discussed on in internal blog https://blogs.mysociety.org/internal/2018/04/27/effect-of-gender-on-contacting-representatives-in-writetothem/) I'd like to run a survey on political knowledge to see how this is interacting with gender in writing to MPs. 

Looking at the old survey removed in https://github.com/mysociety/writetothem/commit/3d2da946367f0f5d49cd3cbc07b516c3b607a530, i've had a go at re-adding a survey that reports to surveygizmo rather than our survey framework. 

That attempt can be found here: https://github.com/mysociety/writetothem/commit/44c6552fa45f9439d66a41e0053f073f5bab1ddf

HOWEVER, I have to point at this point my PHP-knowledge is... low. So I'm putting this as an issue rather than a pull request for the moment because this is might take more than a quick review. 

Basically, looking for:

1. Agreement with placement of survey (or any other discussions about if what I'm trying to do is the best approach).
2. Rough approximation of how much work/time is between what I've done and a working version (and where that would fit on the current plan). 

How this should be working:

firsttime.php l 40-49:

On the page arrived at after people click the questionnaire link, if the person wrote to their MP, it adds the survey from the 'pol-info-survey' template. 
This will appear half the time to start with, and we should adjust downwards if the conversion rate is very high (I'd like to have a reasonable set of data sooner in this case, but also this can be balanced against other factors). 

Line 287 in pol-info-survey passes the message id to the surveygizmo form. 

This whole form is a stripped down version of the template provided by surveygizmo - so a lot of redundant class structure, etc. I didn't want to do too intensive a job pruning it in case I needed to adjust the form and start again, but tested it works without the javascript components. 

This survey will submit the response to surveygizmo (with validation issues being addressed there). 

Why it might not be working:

1. - I've stripped down a lot of the html in surveygizmo generic form, but don't have a good way of testing what this looks like inside the WTT template.
2. - I'm only guessing at how the $values[] is working - if 'recipient_type' or 'id' doesn't do what I think it does, this won't be appearing at all, or passing the id onto surveygizmo.
3. - WTT may have changed since in a way that the old example I'm working from is no longer valid.

**Comment by dracos** [comment]
Needs some design work, but looks like it works okay bar some syntax typos (missing semicolon end of line 42, missing `$ on line 44):

![screen shot 2018-05-09 at 16 10 06](https://user-images.githubusercontent.com/154364/39822827-79ff7f1c-53a3-11e8-804a-cbfeeddaafd7.png)

Placement matches survey done before, and presumably that was okay.

I'm not sure about the passing of the message ID, that seems to provide a direct link to personal data. It would be better if it instead recorded whatever non-personal data it needed from the message table in hidden fields (e.g. recipient ID?).

Assuming you mean the HTML embed function of surveygizmo, I'd hope you don't need to strip that down, did it cause problems if you did?

**Comment by ajparsons** [comment]
My changes to the html embed were mostly taking out references to stylesheets and javascript (it's probably fine with that in, was just checking it wasn't working any magic that required that javascript). 

That makes sense on the message ID, I was thinking that was the easiest way to connect it back up to recipient id and the 'first time' survey response, but you're right I can feed those in separately as hidden fields. 

This is then a secondary priority, but the other nice thing about connecting to the message ID was it then let me check against derived gender and validate how often derived gender accurately matched declared gender (which helps validate the wider conclusions drawn from that). If I uploaded derived gender back as something in the message_extradata table, is it hard to expose that so it can be fed to the form in the same way?

**Comment by dracos** [comment]
I don't think `message_extradata` is exposed anywhere, so yes I imagine that would be work (also, you'd have to automate it for new people answering the survey?). If it's automatable, you could have the survey page compute it and put the answer as another hidden field. If not, you could do something clever like store a hash of the name+secret as a hidden field, then compute hashname+secret -> derived gender lookup to get that info back? Something like that anyway.

**Comment by ajparsons** [comment]
This gets a lot easier if I ignore my offline process for determining gender and just use something like https://genderize.io/ as the control - then I can just compute it on the page. I'll try and get a version of that working.

Question: I'm guessing I can get name like this: <?=$values['sender_name']?>, but how would I get the value for the first use survey response?

**Comment by ajparsons** [comment]
Extra question: What's your opinion on using an iframe to do the embedding?

**Comment by ajparsons** [comment]
Extra question: What's your opinion on using an iframe to embed survey? I can pass the other fields in as url parameters so that seems slightly easier to follow what it's doing.

**Comment by dracos** [comment]
"how would I get the value for the first use survey response?" - that is included in the 'removal of last survey' commit you link to, `questionnaire_1_no` or `questionnaire_1_yes` (seems bit odd way of doing it, but whatever).

"What's your opinion on using an iframe to embed survey?" - meh, presumably bit annoying for the extra scroll bar, but probably wouldn't matter much. I see they also have a JS embed which removes that annoyance if you're happy losing people where that doesn't load.

**Comment by ajparsons** [comment]
Ok, I've replaced all this with the simple javascript version (and giving up on the gender issue for the moment for simplicity) - that's all in https://github.com/mysociety/writetothem/commit/80d12ce5906e87ceb4291ab63987c55336202674

Would now be a good time to transition to a pull request?

Quick clarification on  questionnaire_1_yes - I'd assume this means it is the first time they contacted their rep - but the deleted questionnaire seems to be the other way round:

```
        <? if ($values['questionnaire_1_yes']) { ?>	
            <tr id="id_previouscontact_line">	
              <td class="us_label">	
                <div class="us_label">	
                  You’ve said that this is not the first time you’ve contacted your representative. The last time you’ve contacted your representative, how did you approach him or her?	
                </div>	
              </td>
```

Just want to check I'm right there?

**Comment by dracos** [comment]
Yeah, PR please!
`questionnaire_1_yes` is "Is this the first time? Yes" as far as I can tell, so that previous survey seems wrong, yes.

**Comment by ajparsons** [comment]
PR is: #399
