### ISSUE TITLE
Make https://www.writetothem.com/admin/ redirect to the admin index

### ISSUE THREAD

**Issue by abimysoc** [mysociety/writetothem#406]
`/admin/` is where I'm conditioned to believe the admin interface will be found, because that's where it is on all our other sites...

**Comment by dracos** [comment]
It is the admin index? I mean, you only ever really need three of the pages listed there (queue, non-councillor rep editing, councillor editing), and theoretically another three (two graphs, abuse editing), but if it only directed to the queue, you'd nee a way to get to the others

**Comment by abimysoc** [comment]
Ah! I mean the version without the trailing slash. https://www.writetothem.com/admin doesn't redirect.

**Comment by dracos** [comment]
Fixed

**Comment by MyfanwyNixon** [comment]
Is this why the links in the Quality Deity email don't work now? eg   https://secure.mysociety.org/admin/fyr/?page=reps&bad_contacts=1

**Comment by dracos** [comment]
No, that was https://github.com/mysociety/writetothem/issues/404 which I've also fixed.

**Comment by MyfanwyNixon** [comment]
Oh ok so future emails won't have this problem? Thanks.
