### ISSUE TITLE
No confirmation link

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#415]
Well here's a blast from the past (see #56 and #155). A user forwarded the confirmation email because there was no link to press. Email domain is protonmail.com.

From the forwarded mail, the button appears as unclickable plain text and there are also some formatting issues.

![screenshot_2018-11-27 fwd please confirm that you want to send a message to alberto costa mp - writetothemsupport mysociety](https://user-images.githubusercontent.com/944656/49073344-25b57f80-f22a-11e8-96a7-2ce1e09a2a90.png)

**Comment by MyfanwyNixon** [comment]
Further from the user:
>the usual option to allow external links/download external images wasn’t present so I think it was a malformed email.

**Comment by dracos** [comment]
I have just sent myself a confirmation email to my protonmail account and it displays fine.
