### ISSUE TITLE
Make it clear that responsiveness stats are no longer up to date

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#422]
Every now and then we get a handful of emails saying our MP information is out of date. When asked, the users then explain that they've entered the site via the zeitgeist page. Although the year is stated at the top of the page, it obviously doesn't stand out enough for these folk to notice it - can we introduce a design element and some explanatory text to these pages?

Related - I'm not sure now why I closed #74.

**Comment by MyfanwyNixon** [comment]
A user wrote:
>This site is out of date by several years. Byron Davies is no longer our MP and I have never written to him so info received from me is not relevant. 

Maybe we should take these stats pages down.

**Comment by MyfanwyNixon** [comment]
A user:
> Has the table been abandoned?  If so may I suggest you update the FAQ and explain why ... or, even better, flip on the switch which will update the table :-)

**Comment by MyfanwyNixon** [comment]
https://twitter.com/jabberwocky38/status/1243166742526005250

**Comment by MyfanwyNixon** [comment]
We've had another spate of emails asking about this. Can we just taken them away or write a blog post and link to it, explaining why we're no longer updating? (@ajparsons perhaps?)

**Comment by ajparsons** [comment]
Linked to https://github.com/mysociety/theyworkforyou/issues/1467

**Comment by ajparsons** [comment]
Also linked to: https://github.com/mysociety/writetothem/issues/424

**Comment by ajparsons** [comment]
We have the blog post on this for a few weeks time, is a change to the FAQ everything else that's needed?

**Comment by abimysoc** [comment]
`templates/emails/questionnaire` and `templates/emails/questionnaire.html` both refer to the stats. I made it vaguer by removing the direct link to the stats page in May (#441) but please consider whether further changes are needed to fend off the inevitable 'why are you asking for this data when you don't do anything with it?' questions.

**Comment by MyfanwyNixon** [comment]
>Your feedback allows us to check that the service is working, and alerts us to potential issues.

might be enough.

**Comment by ajparsons** [comment]
My suggestions:

### Questionnaire

Replace:

Your feedback allows us to analyse the responsiveness of all the politicians in the UK. We are keen to give politicians the credit  they deserve when they respond promptly to their constituents. We think it's also worth highlighting the representatives who don't.

With:

Your feedback allows us to analyse the responsiveness of politicians in the UK. We use this information to check that the service is working, alert us to potential issues, and perform research into how responsive politicians are to contact from constituents. 

### FAQ

Replace:

It’s a ranking, listing all MPs, together with the number of WriteToThem messages they replied to, based on your questionnaire responses. You can see more (including how we compile it, and the caveats you ought to be aware of) on our stats page

With:

The responsiveness league table was an annual ranking of representatives according to how responsive they were to constituent contact. We discontinued this in 2017, and have blogged about this and our research into replacement measures. [with link to blog]

**Comment by ajparsons** [comment]
Blog now exists, so will create a PR for this change.

**Comment by MyfanwyNixon** [comment]
Thanks!
