### ISSUE TITLE
Deceased peer

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#423]
> I was informed that  Baroness Gibson of Market Rasen was deceased after I wrote to her.
> Maybe update your records.

Relevant to #414

**Comment by abimysoc** [comment]
Deleted, anyone with access to the admin interface can do this.

**Comment by dracos** [comment]
She'll come back at the weekend though if not removed from TheyWorkForYou (from which WTT syncs weekly).
