### ISSUE TITLE
Survey email still talks about stats

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/writetothem#424]
The survey email sent to users two weeks after writing a message still mentions that stats are collected and performance tables published – this isn't a thing which has happened since 2015/16.

**Comment by MyfanwyNixon** [comment]
See #74 as well.
So - the wider question is whether we still want to collect the stats at all. 

If not, do we even carry on sending the surveys?

If so, we should say why - I assume it's partly to do with ensuring the site is working and partly for our own research.

**Comment by jacksonj04** [comment]
Paging @ajparsons who may have something useful to add.

**Comment by ajparsons** [comment]
I'd like to keep collecting the results (but open to longer discussions about that) but we should probably stop promoting the tables.

Similarly they're promoted as part of TWFY's numerology section - which makes that look out of date.

**Comment by abimysoc** [comment]
Ah yes, my #441 fixed this a few weeks back.
