### ISSUE TITLE
No more MEPs

### ISSUE THREAD

**Issue by ajparsons** [mysociety/writetothem#436]
The UK no longer has MEPs, so this section on the results page should be removed.

**Comment by dracos** [comment]
Replaced with message for now

**Comment by abimysoc** [comment]
Is it possible that this change could have broken the functionality to write to multiple representatives? It does seem to be broken at the moment. When I click 'Write to all your district councillors' I just get a blank page. Also borrowed a Scottish postcode to test for MSPs, and a Welsh one for AMs, same thing.

Happy to re-close this and ticket separately if it's a different bug :)

**Comment by dracos** [comment]
Hasn't been any other changes, so presumably must be! Just looking

**Comment by dracos** [comment]
Sorry about that, now fixed.
