### ISSUE TITLE
Rename National Assembly for Wales

### ISSUE THREAD

**Issue by luketainton** [mysociety/writetothem#440]
<img width="392" alt="Screenshot 2020-05-24 at 12 37 01" src="https://user-images.githubusercontent.com/22561713/82753132-462cae80-9dbb-11ea-93c9-f2c067b33bd7.png">

The National Assembly for Wales has been renamed to Senedd. All references to the National Assembly should be renamed to reflect the change.

**Comment by dracos** [comment]
Thanks for your report; should now be fixed by bca2845e12ef452bbed0ad7a1893b58c50bc5ce4
