### ISSUE TITLE
Numbers of messages sent

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#447]
Please could someone run a query to see:
- How many messages were sent during the week 1-7 Jun 2020
- How this compares with the same week in 2019, and/or an average week.
- How many messages were sent in the week 17-23 May (our previous peak in page views)
- If possible, how many messages were sent 31 Oct - 6 Nov 2016 (also a peak)
Thanks!

**Comment by MyfanwyNixon** [comment]
Additionally from @markcridge : can we break it down by type of representative please?

**Comment by ajparsons** [comment]
Detailed on this sheet with a graph: https://docs.google.com/spreadsheets/d/1EFnNVC12JMhUPYf5Z-QzipG7J-j4aBf8VLMsEHUfHBs/edit#gid=0

![image](https://user-images.githubusercontent.com/8157058/84496552-0a438580-aca5-11ea-8672-b253b8729492.png)


Chart gives broad picture of this very big peak. Tab 3 lets you sort by week and type to see biggest over all time. 

- Week 23 (1-7 June) was the highest ever week. 21,604 messages were sent to MPs. The second highest is the week before. 
- An average week in 2019 (including an election) was 1,672. 
- Week 44 2016 (31 oct to 6 nov) was 4317 (week 45 was about 10,000 though)
