### ISSUE TITLE
Many Siân Gwenllians

### ISSUE THREAD

**Issue by abimysoc** [mysociety/writetothem#461]
Siân Gwenllian, Senedd rep for Arfon, exists at least 20 times in our database with different representative IDs, resulting in https://www.writetothem.com/who?pc=LL54+6AH

I have no doubt something weird is going on as a result of that 'â', as her name is most often displayed in the admin as Si�n.

**Comment by MyfanwyNixon** [comment]
Possibly related? Also a duplicated Senedd member: https://twitter.com/JoeRhisga/status/1348542785461366784

<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/mySociety?ref_src=twsrc%5Etfw">@mySociety</a> hello pawb. Seems to be a bug on writetothem - one of my Welsh Parliament members comes up twice <a href="https://t.co/46LsL0obmD">pic.twitter.com/46LsL0obmD</a></p>&mdash; Joe o Risga (@JoeRhisga) <a href="https://twitter.com/JoeRhisga/status/1348542785461366784?ref_src=twsrc%5Etfw">January 11, 2021</a></blockquote>

**Comment by dracos** [comment]
Fixed bad database entries; will watch out for what happens once election results are out.
