### ISSUE TITLE
Stop appending 'MS' to constituency Senedd members' names

### ISSUE THREAD

**Issue by abimysoc** [mysociety/writetothem#462]
Constituency (not regional, just constituency) Senedd members are in the database as, e.g. 'Paul Davies MS' rather than just 'Paul Davies'.

If you edit the representative to remove MS from the name, it appears that something automated comes along and creates a new 'Paul Davies MS', and then there are two of them.

'MS' shouldn't be part of the name, because it leads to things like this:

![image](https://user-images.githubusercontent.com/560001/104432435-ee78c880-5580-11eb-87bf-422ed68fd247.png)

**Comment by dracos** [comment]
I've disabled the Senedd import, once the election results are out and it's on their website, I will check the output strips the MS before import.

**Comment by dracos** [comment]
This is resolved
