### ISSUE TITLE
Actually discard email sent to do-not-reply address

### ISSUE THREAD

**Issue by abimysoc** [mysociety/writetothem#470]
If someone emails the do-not-reply address from which our confirmation/questionnaire emails are sent, their email gets through to the support inbox.

Stats in the last 4 weeks:

276 spam
19 users' out-of-office/other autoresponses
7 people replying to the questionnaire, in each case to tell us their questionnaire answer instead of clicking on one of the links in the email
20 people replying to the confirmation email (7 completely blank, 3 people replying "Yes" instead of clicking the link, 9 correspondence intended for the representative, 1 genuine question for WTT support)

The spam:not-spam ratio is enough alone to justify discarding mail to this address.

**Comment by dracos** [comment]
Just to note it's not all emails that get through; if the email contains a confirm/questionnaire URL it auto-replies to the user to tell them to click the link. The (real) ones that got through either replied to that reply or their email was encoded so it didn't spot the links. But yes, all the spam won't be having the links in them, so have opened #471 to drop it all.
