### ISSUE TITLE
Deleted MP keeps returning

### ISSUE THREAD

**Issue by abimysoc** [mysociety/writetothem#473]
Cheryl Gillan MP died in early April. She's been deleted from WriteToThem via the admin at least twice, with Vacant Seat added so that the website front end displays the right thing, but `dadem_csv_load` script keeps putting her back.

**Comment by dracos** [comment]
You don't need to do Vacant Seat for them, that's only for councillors. The constituency is marked as pending, so nothing will appear in the front end. So it doesn't actually matter if she's present in the db or not. But yes, I'll look at it!
