### ISSUE TITLE
Disallow sending of emails with no content

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#478]
We've had a few examples of messages to councillors that contain no content this week, and it's something I recall being reasonably common through the years. 

Presumably this is a user error, although it seems like a baffling one given that the user is shown their 'message' and asked to confirm it both on the site and via the confirmation email.

Can we detect when there's no content between the salutation and the signature and prevent those messages being sent?

**Comment by dracos** [comment]
There already is such a check: https://github.com/mysociety/writetothem/blob/master/web/write.php#L206-L207
So I think I'd need to see actual examples to know if/why that's not firing.

**Comment by dracos** [comment]
Looks like there is a bug in that the ordering of the Dear line is not consistent, so if it's to multiple people and the check order differs from the submitted order, that counts as "editing" the content. Could change the check to not care what is on the Dear line easily enough I think.

**Comment by dracos** [comment]
Made it treat any Dear line as the same, so should count these blanks now.

**Comment by MyfanwyNixon** [comment]
Looks like another has come through somehow, today. ID 3f52f4a3c96d1ffef5f3.

**Comment by dracos** [comment]
Was tweaked to fix this
