### ISSUE TITLE
Link directly to email compose page

### ISSUE THREAD

**Issue by alexvdvalk** [mysociety/writetothem#496]
Your current email compose page url looks like this: https://www.writetothem.com/write?who=92851&pc=SW17+0AA

I'd like to create a link directly to this page from my website, but I'd need to have a lookup of the MPs and your corresponding MP ID. I've tried using your MP ID on the https://members-api.parliament.uk/ API but your IDs don't work here.

Is this list of MPS / MP ID exposed somewhere?

**Comment by dracos** [comment]
We do not wish to enable direct linking to the compose page, it is not supported. To link to WriteToThem, please use one of the options given at https://www.writetothem.com/about-linktous . For MPs alone, for example, you could use the information at https://www.writetothem.com/about-linktous#types

**Comment by alexvdvalk** [comment]
Thanks for the quick response. ok this could work.
