### ISSUE TITLE
Confirmation link difficult for some users

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#56]
Comment from user, 21.1.13:

I do wish to send the letter [..] but am unable to click on the link and have no idea how to paste it to my web browser. Why does sending an MP an e-mail have to be so complicated?

**Comment by MyfanwyNixon** [comment]
Gmail user: "I am unable to click the link  - it’s not blue"

**Comment by MyfanwyNixon** [comment]
"You need to sort out your link for iphones. I have tried to copy and paste but it doesn't work."

**Comment by jacksonj04** [comment]
I'm almost tempted to close this as a won't fix. HTML email would (in theory) solve it, and if the problem happens on so many platforms in a basically unreplicatable manner I have no idea at all how to go about diagnosing it, let alone fixing it.

**Comment by MyfanwyNixon** [comment]
btinternet user: "The link to confirm my email to Cllrs was not blue so could not complete the email. Please advise as to how I can confirm now? Another email?!!!"

**Comment by MyfanwyNixon** [comment]
Hotmail user: "First I opened this email in Firefox and the link wouldn't work. I re-opened my email in Googlechrome and the link worked."

**Comment by MyfanwyNixon** [comment]
"Unable to click on link?? Please advise." - BT Internet user on Windows Mail

**Comment by MyfanwyNixon** [comment]
"Link not working, please send email to [MP]"

BT internet

**Comment by MyfanwyNixon** [comment]
"It would be helpful if you actually sent a working link - especially since neither of my web-browsers can use what you did send." Windows Mail & Talk Talk

**Comment by MyfanwyNixon** [comment]
"I could not click on the “confirmation” link but wrote it in instead and got a whoops something hasn’t worked response" - talktalk, Windows mail

**Comment by MyfanwyNixon** [comment]
Pretty sure now that this is a Windows Mail problem, if not exclusively then certainly enough for us to treat it as an issue in itself.Latest instance from a yahoo.co.uk user on Windows Mail who got in touch because the link 'didn't work' and she didn't know how to copy and paste.

**Comment by MyfanwyNixon** [comment]
Windows Mail:
>Please don’t worry about sending me links to click to confirm I want my letters sent. I cannot click the links it does not work for some reason, and I don’t know how to copy and paste, despite being told how to do this, I cannot get that to work either. Please feel free to sund send my letters on with asking me to confirm each time, as I’m afraid I can’t unless the link is sent in a different format. 

This makes me sad :(

**Comment by MyfanwyNixon** [comment]
Two more users couldn't click the link today (neither appear to be using Windows Mail, or at least it doesn't include that suffix, although the issue could be the same, ie disabled links):

> As I was not able to use the  Link I did not proceed so please cancel. 

(ntl world, they forwarded the mail and the link looks fine)

> Tried clicking the link but did not work 

(sky.com)

**Comment by jacksonj04** [comment]
I think it's pretty obvious at this point that it's something happening client side, which I guess makes a fix all that more awkward since nobody seems to be able to reproduce it.

**Comment by MyfanwyNixon** [comment]
OK I'm currently replying to everyone to look out for an 'enable links' functionality, or similar. Let's see how much that helps.

**Comment by MyfanwyNixon** [comment]
I'm closing this issue, as the theory about Windows mail, Hotmail and some other email programmes appears to be the answer. A minority of people also just find the entire confirmation process annoying/puzzling, and those comments will from now on be recorded on #288.

**Comment by MyfanwyNixon** [comment]
> message asking me if i really wanted to write to my MP after
     all....well call me Mr indecisive, but if I take the trouble to
     write to someone it's because that's what I want to do - i.e.
     WRITE TO THEM

>     Please do not patronise the electorate by asking them if they
     are serious...is this some kind of Kindergarten scheme?

**Comment by MyfanwyNixon** [comment]
Just another data point from a user of BT Internet:

> I Sent my email to a Peter Lilley yesterday and confirmed that to you yet you keep sending me emails to say I need to send it. Why does the process have to be so complicated? It really puts me off using your website.

According to our system she had not in fact confirmed.

**Comment by MyfanwyNixon** [comment]
> You do not make it easy to send the  MP my e.mail as I have no idea how to paste and copy  I hope yku will send it now .

**Comment by MyfanwyNixon** [comment]
> Your message asked me to "click on the link below"  :  there
     were three to choose from but I tried the first.     It
     provided no apparent means of sending my message and the other
     two have titles which make them seem irrelevant to sending my
     message.  If my merely clicking on that link was to result in
     my message being sent you should have said so.
     I cannot remember the difficulties I encountered yesterday when
     I wrote my message but the process was not intuitive and now
     this.
     You are providing a useful service in principle but my
     experience deters me from using it again.

This was a TalkTalk email account; sad if we are actively deterring users.

**Comment by MyfanwyNixon** [comment]
We are now delivering HTML emails.

Our most frequent user support correspondent has reported problems with the confirmation link, both before and after the change. Unfortunately, efforts to get her to describe precisely what the problem is have been unsuccessful, beyond the fact that it 'doesn't work' and she's on a Samsung tablet.

Today another user writes, from an aol account "Cannot find or operate confirmation link for either letter I  have done with you. "

I've written to ask him to let us see the email, and/or give a bit more detail.

**Comment by MyfanwyNixon** [comment]
The user above replied:
> I am using a Windows Lumia Phone 640. There is no confirmation button that I can find in the e-mail. 

And forwarded the email, in which I could clearly see a functional button - so I'm guessing this is back to the 'aol block what they perceive to be dangerous links' problem?

**Comment by MyfanwyNixon** [comment]
I suspect we are having trouble with the same email providers as before, ie AOL, BTInternet and Yahoo :(

**Comment by MyfanwyNixon** [comment]
From the Windows phone user:
>For some reason the Windows phone I use on the go does not show either blue logo or confirmation button.

**Comment by MyfanwyNixon** [comment]
A screenshot!

![hotmail](https://cloud.githubusercontent.com/assets/944656/23300244/98bfc672-fa7c-11e6-9b74-1678bd0f9055.png)

**Comment by dracos** [comment]
That's only because their quoting of the message cuts off at the point where it says "The entire original message is not included", I don't think that's related to anything here (and if it were, it would be a new ticket :) ).

**Comment by MyfanwyNixon** [comment]
Oh, ha! As you were then.

**Comment by MyfanwyNixon** [comment]
Although, perhaps worth noting that this was an email where the user had replied to tell us 'yes'.
