### ISSUE TITLE
User suggestion - layout not clear

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#60]
(User got in touch to say that his own local LA member was not on the page - she was, but separated from the rest because she was "his" rep)

"I had scanned the page you linked to: when I saw "Write to all your London Assembly list members" I assumed that was my only option for writing. I didn't tumble that I could write to individuals just by clicking their names.

Just a thought - you could rephrase that page so it reads "Or, write to all your London Assembly members" - might help numpties like me realise you can write to them individually. "

**Comment by dracos** [comment]
Predates redesign.
