### ISSUE TITLE
Third option in the questionnaire

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#61]
Our text currently reads 'If you feel that neither link is suitable, then please do not answer the questionnaire. '

Comment from user: "Your recommended action in my case is to do nothing, which I'm happy with. However you keep sending the questionnaire.... My preference would be for a third option - "I'm happy - no further action required".

This link would need to switch off the questionnaire reminder.

Related to #11 

Happiness is quite subjective, so wording might need to be 'no reply was required' (whilst preventing the questionnaire from becoming overly long/confusing).

**Comment by abimysoc** [comment]
Fixed by #311.
