### ISSUE TITLE
User suggestion: user accounts

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#70]
Feedback from user:

"I'm finding it trickt to find copies of the letters I write to my MP.  Replies from Ministers always takes months and then I have lost the original - My bad practice I realise. But if I had an account with writetothem I could simply look and find the letters I've sent..."

**Comment by Gemmamysoc** [comment]
User feedback: Is there any way that you can upgrade the website so that it remembers my name, e'mail address and home address?  Many other websites I use seem to save that data somewhere on my PC and post it when needed. It is the only thing I find which detracts from an excellent online service.

**Comment by dracos** [comment]
I would suggest they use their browser's autocomplete functionality to remember fields like that (e.g. perhaps if they hit down arrow in the box it will show name as an example). I don't think we want to have accounts, because of the privacy implications, as above.
