### ISSUE TITLE
Downloadable lesson plans

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#72]
As discussed with @JenMysoc - we should get a teacher/ mySoc volunteer to write a lesson plan that centres around the use of WTT and TWFY, clearly positioning it within the curriculum. 

We could then offer this as a downloadable resource - it could be adapted for adult access to ICT learners too.

**Comment by MyfanwyNixon** [comment]
Hooray: please point your interested teacher friends towards https://www.mysociety.org/lesson-plans/.

**Comment by mhl** [comment]
Great, I've forwarded that link on :)
