### ISSUE TITLE
Issues with the questionnaire links

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/writetothem#98]
Two users saying the links don't work; one via the Times, the other v2 of WTT:

[snipped links because they probably shouldn't be public]

**Comment by MyfanwyNixon** [comment]
Another one, on Tiscali this time. "The link doesn't work"

**Comment by abimysoc** [comment]
Let's optimistically assume that all these issues have been resolved by #342 and open a new ticket if there's any feedback about the HTML ones...
